# Generated by Django 5.0.4 on 2024-04-27 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('haqida', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Muallif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=255)),
                ('tirik', models.BooleanField(default=False)),
                ('mamlakat', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('yil', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='')),
                ('bolim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.bolim')),
                ('muallif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.muallif')),
            ],
        ),
    ]
